databases:
  - name: sqlite3
    ipAllowList: []

services:
  - type: web
    name: mysite
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: sqlite3
          property: connectionString
